### ISSUE TITLE
Feature request - highlight lowest defence boss instead

### ISSUE THREAD

**Issue by kingoomieiii** [bloogeyz/nmz-optimal-points#3]
Or maybe a separate plugin. I say feature because it's the same thing but with another column in the .csv.

**Comment by bloogeyz** [comment]
I've added this in and it's been pushed to live. You should now see a "Rank By Defense" checkbox in the config. 

Let me know if you encounter any issues

![image](https://user-images.githubusercontent.com/37584994/112484484-e358ca80-8d71-11eb-9446-58a0f870bb82.png)
