### ISSUE TITLE
Flashing Hulls. **Fixed**

### ISSUE THREAD

**Issue by Newt-Tea** [bloogeyz/nmz-optimal-points#5]
Whenever I'm in NMZ the hulls flash on and off and sometimes switch colors even when I haven't killed any of the bosses I only haver highlight hulls on and I have all 4 bosses highlighted

**Comment by bloogeyz** [comment]
I'll look into this.

**Comment by bloogeyz** [comment]
![INuDVVgVPQ](https://user-images.githubusercontent.com/37584994/112719215-af0b1880-8eef-11eb-9009-73a58df2a370.gif)

Think I've reproduced it, let me know if this is your issue and I'll work on this one regardless.

**Comment by Newt-Tea** [comment]
yep that was the problem i had i'll check to see if fixed tommorow
