### ISSUE TITLE
Highlight Outline

### ISSUE THREAD

**Issue by natewiebe13** [bloogeyz/nmz-optimal-points#7]
Runelite recently introduced a new model outline renderer: https://runelite.net/blog/show/2021-07-14-1.7.16-Release/

The `NPC Indicators` includes an option `Highlight outline` that can be used instead of `Highlight hull` along with a width and feather option.

It would be great to have these same features in this plugin.

**Comment by natewiebe13** [comment]
Here's the commit where the outline renderer was added to the NPC Highlight plugin: https://github.com/runelite/runelite/commit/887193148a281b6f437fcf973863dd0b3678bc84

**Comment by bloogeyz** [comment]
Thanks, I will take some time to implement this next week.
